//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrderBaseInfo
    {
        public System.Guid InfoID { get; set; }
        public string OrderNO { get; set; }
        public string OUCode { get; set; }
        public string Foreman { get; set; }
        public string IndoorGuarder { get; set; }
        public string OutdoorGuarder { get; set; }
        public string Chief { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string JobItems { get; set; }
        public string WorkId { get; set; }
        public string CmdNum { get; set; }
        public string STA_ID { get; set; }
        public Nullable<byte> SourceType { get; set; }
        public string DEP_ID { get; set; }
        public string JobType { get; set; }
        public string WorkType { get; set; }
        public string ShiftLeader { get; set; }
        public string ToolManager { get; set; }
        public string CmdNumAgain { get; set; }
        public string EntryName { get; set; }
        public string ExportName { get; set; }
    }
}
